name: gplanetary-nav
channels:
    - anaconda
    - conda-forge
    - astropy
dependencies:
    - python=3.7
    - pip=22.2
    
    - numpy=1.19
    - rasterio=1.1
    - scikit-image=0.19
    - networkx=2.5
    - scipy=1.7
    - pandas=1.3
    - numba=0.55
    - pyyaml=5.4
    - astroquery=0.4 
    - jdcal=1.4
    - gdal=3.1
    - matplotlib-base=3.5 # unlike matplotlib, does not install Qt
    - av=9.2
    
    - pip:
        - hkb_diamondsquare
        - -e . # build local gplanetary_nav package
